### ISSUE TITLE
Please drop greenkeeper.

### ISSUE THREAD

**Issue by jamestalmage** [ariporad/pirates#25]
I currently watch pirates, and it is badly polluting my GitHub feed.

Just use [`david`](https://github.com/alanshaw/david) to make sure things stay up to date.

**Comment by sindresorhus** [comment]
:+1:

**Comment by ariporad** [comment]
Ok, will do when I get back to my laptop.

**Comment by ariporad** [comment]
@jamestalmage, @sindresorhus: Done.
